openapi: 3.0.0
info:
  title: BOQ system apis
  description: you will get here the complete detail and implementation of BOQ system apis.
  version: 0.1.9
servers:
  - url: http://localhost:8000/
    description: for running on localhost
  - url: http://boq.cybersynctech.com
    description: use after deployment of the system
components:
  securitySchemes:
    ApiToken:        # arbitrary name for the security scheme
      type: http
      scheme: basic
    # ApiKey:        # arbitrary name for the security scheme
    #   type: apiKey
    #   in: header       # can be "header", "query" or "cookie"
    #   name: apikey  
paths:
  /:
    get:
      tags:
        - welcome home
      summary: Returns message for welcome to boq system.
      description: for only checking the server is up and running.
      responses:
        '200':    # status code
          description: OK

  /signUp:
    post:
      tags:
       - SignUp
      summary: Creates a new user.
      description: sign up for new users through email address and password
      parameters:
        - name: username
          in: path
          required: true
          description: The username of the user.
          schema:
            type: string
            example: Dawood
        - name: email
          in: path
          required: true
          description: The email of the user.
          schema:
            type: string
            example: Dawood@cst.com
        - name: position
          in: path
          required: true
          description: The position of the user.
          schema:
            type: string
            example: civil engineer
        - name: password
          in: path
          required: true
          description: The password user enter.
          schema:
            type: string
            example: engineer
        - name: retypePassword
          in: path
          required: true
          description: The retypePassword user enter for conforming the password given and must be same to passwrod.
          schema:
            type: string
            example: engineer
      post:     
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: Dawood 
                email: 
                  type: string
                  example: dawoodisrar@gmail.com
                position:
                  type: string
                  example: constructing engineer
                password: 
                  type: string
                  example: hey123
                retypePassword:
                  type: string
                  example: hey123

               
      responses:
        '500':
          description: internal server error
        '201':
          description: Created
  /logIn:
    post:
      tags:
       - logIn
      summary: Log in with user email and password.
      description: login for new users through email address and password
      parameters:
        - name: email
          in: path
          required: true
          description: The email of the user register.
          schema:
            type: string
            example: dawoodisrar@gmail.com
        - name: password
          in: path
          required: true
          description: The password user enter.
          schema:
            type: string
            example: engineer
      post:     
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: 
                  type: string
                  example: dawoodisrar@gmail.com
                password: 
                  type: string
                  example: hey123
               

               
      responses:
        '500':
          description: internal server error
        '201':
          description: login Successfully
  /auth/google:
    get:
      tags:
       - logIn with google
      summary: Log in with user google account.
      description: login for new user through google account
      
      responses:
        '500':
          description: internal server error
        '201':
          description: login Successfully
  # /materials:
  #   post:
  #     tags:
  #      - Estimate material
  #     summary: Estimate overall material
  #     description: Estimate overall material including total bricks, total cements bags, total sand volume, total concrete for roof, total steel in kilogram for roof.
  #     parameters:
  #       - name: name
  #         in: path
  #         required: true
  #         description: Enter the name of the project of estimation the material.
  #         schema:
  #           type: string
  #           example: Dawood vella
  #       - name: area
  #         in: path
  #         required: true
  #         description: total Surface area for construction of building.
  #         schema:
  #           type: float
  #           example: 2000
  #       - name: no_of_roofs
  #         in: path
  #         required: true
  #         description: Enter the total number of roof you want to construct in the building.
  #         schema:
  #           type: integer
  #           example: 2
  #       - name: rooms
  #         in: path
  #         required: true
  #         description: Enter total rooms you want to construct in the building.
  #         schema:
  #           type: string
  #           example: civil engineer
  #       - name: avg_room_size
  #         in: path
  #         required: true
  #         description: The average room size for all the room in the building.
  #         schema:
  #           type: float
  #           example: 200
  #       - name: attach_bath
  #         in: path
  #         required: true
  #         description: If you want to have attach bathroom with every room make it true.
  #         schema:
  #           type: boolean
  #           example: true
  #       - name: avg_bath_size
  #         in: path
  #         required: false
  #         description: If you want to have attach bathroom with every room and want to give specific bath room size for it By defualt size is 5x6 => 30 feet.
  #         schema:
  #           type: flaot
  #           example: 30
  #       - name: kitchen
  #         in: path
  #         required: true
  #         description: If you want to have one  kitchen with every roof.
  #         schema:
  #           type: boolean
  #           example: true
  #       - name: kitchen_size
  #         in: path
  #         required: false
  #         description: If you want to have kitchen  with every roof and want to give specific kitchen  size for it By defualt size is 10x20 => 120 feet.
  #         schema:
  #           type: flaot
  #           example: 130
  #       - name: ratio
  #         in: path
  #         required: true
  #         description: Ratio for the roof material in the following M5,M10,M15,M20,M25)
  #         schema:
  #           type: String
  #           example: M15
  #       - name: u_id
  #         in: path
  #         required: true
  #         description: User id
  #         schema:
  #           type: integer
  #           example: 1
  #     post:     
  #     requestBody:
  #       required: true
  #       content:
  #         application/json:
  #           schema:
  #             type: object
  #             properties:
  #               name:
  #                 type: string
  #                 example: Dawood vella 
  #               area: 
  #                 type: float
  #                 example: 2000
  #               no_of_roofs:
  #                 type: integer
  #                 example: 2
  #               rooms: 
  #                 type: integer
  #                 example: 3
  #               avg_room_size:
  #                 type: float
  #                 example: 220
  #               attach_bath:
  #                 type: boolean
  #                 example: true
  #               attach_bath_size:
  #                 type: float
  #                 example: 30
  #               kitchen:
  #                 type: boolean
  #                 example: true
  #               kitchen_size:
  #                 type: float
  #                 example: 120
  #               ratio:
  #                 type: string
  #                 example: M15
  #               u_id:
  #                 type: integer
  #                 example: 1
 
  #     responses:
  #       '500':
  #         description: internal server error
  #       '200':
  #         description: OK


  /materials:
    post:
      tags:
       - Estimate material
      summary: Estimate overall material
      description: Estimate overall material including total bricks, total cements bags, total sand volume, total concrete for roof, total steel in kilogram for roof.
      parameters:
        - name: name
          in: path
          required: true
          description: Enter the name of the project of estimation the material.
          schema:
            type: string
            example: Dawood vella
        - name: area
          in: path
          required: true
          description: total Surface area for construction of building.
          schema:
            type: integer
            example: 2000
        - name: no_of_roofs
          in: path
          required: true
          description: Enter the total number of roof you want to construct in the building.
          schema:
            type: integer
            example: 2
        - name: rooms
          in: path
          required: true
          description: Enter total rooms you want to construct in the building.
          schema:
            type: string
            example: civil engineer
        - name: avg_room_size
          in: path
          required: true
          description: The average room size for all the room in the building.
          schema:
            type: integer
            example: 200
        - name: attach_bath
          in: path
          required: false
          description: If you want to have attach bathroom with every room make it true.
          schema:
            type: boolean
            example: false
        - name: avg_bath_size
          in: path
          required: false
          description: If you want to have attach bathroom with every room and want to give specific bath room size for it By defualt size is 5x6 => 30 feet.
          schema:
            type: flaot
            example: 30
        - name: kitchen
          in: path
          required: false
          description: If you want to have one  kitchen with every roof.
          schema:
            type: boolean
            example: true
        - name: kitchen_size
          in: path
          required: false
          description: If you want to have kitchen  with every roof and want to give specific kitchen  size for it By defualt size is 10x20 => 120 feet.
          schema:
            type: flaot
            example: 130
        - name: ratio
          in: path
          required: true
          description: Ratio for the roof material in the following M5,M10,M15,M20,M25)
          schema:
            type: string
            example: M15
        - name: u_id
          in: path
          required: true
          description: User id
          schema:
            type: integer
            example: 1
    
      post:     
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Dawood vella 
                area: 
                  type: float
                  example: 2000
                no_of_roofs:
                  type: integer
                  example: 2
                rooms: 
                  type: integer
                  example: 3
                avg_room_size:
                  type: float
                  example: 220
                attach_bath:
                  type: boolean
                  example: true
                attach_bath_size:
                  type: float
                  example: 30
                kitchen:
                  type: boolean
                  example: true
                kitchen_size:
                  type: float
                  example: 120
                ratio:
                  type: string
                  example: M15
                u_id:
                  type: integer
                  example: 1
 
      responses:
        '500':
          description: internal server error
        '200':
          description: OK